# Laboratório 4 - Pré-processamento de dados
Filipe Gomes Arante de Souza

1. Carregue a base iris e a separe em treino e teste usando 40% dos exemplos para teste. Reduza a
base de treino para ter apenas os 24 exemplos iniciais e a de teste para ter apenas os 16 exemplos
iniciais. Considere que o valor 1.5 representa um elemento ausente. Substitua as ocorrências de
valores ausentes pelo valor mais frequente nas bases de treino e de teste reduzidas.

In [1]:
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split

iris = datasets.load_iris()

df = pd.DataFrame(data = iris.data)
df

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [2]:
X_train, X_test, y_train, y_test = train_test_split(
    iris.data, iris.target, test_size=0.4, random_state=0)

new_X_train = X_train[:24]
new_y_train = y_train[:24]

new_X_test = X_test[:16]
new_y_test = y_test[:16]

df_X_train = pd.DataFrame(data = new_X_train)
df_y_train = pd.DataFrame(data = new_y_train)

df_X_test = pd.DataFrame(data = new_X_test)
df_y_test = pd.DataFrame(data = new_y_test)

print('Base de treino reduzida:')
print(df_X_train)
print(df_y_train)

Base de treino reduzida:
      0    1    2    3
0   6.0  3.4  4.5  1.6
1   4.8  3.1  1.6  0.2
2   5.8  2.7  5.1  1.9
3   5.6  2.7  4.2  1.3
4   5.6  2.9  3.6  1.3
5   5.5  2.5  4.0  1.3
6   6.1  3.0  4.6  1.4
7   7.2  3.2  6.0  1.8
8   5.3  3.7  1.5  0.2
9   4.3  3.0  1.1  0.1
10  6.4  2.7  5.3  1.9
11  5.7  3.0  4.2  1.2
12  5.4  3.4  1.7  0.2
13  5.7  4.4  1.5  0.4
14  6.9  3.1  4.9  1.5
15  4.6  3.1  1.5  0.2
16  5.9  3.0  5.1  1.8
17  5.1  2.5  3.0  1.1
18  4.6  3.4  1.4  0.3
19  6.2  2.2  4.5  1.5
20  7.2  3.6  6.1  2.5
21  5.7  2.9  4.2  1.3
22  4.8  3.0  1.4  0.1
23  7.1  3.0  5.9  2.1
    0
0   1
1   0
2   2
3   1
4   1
5   1
6   1
7   2
8   0
9   0
10  2
11  1
12  0
13  0
14  1
15  0
16  2
17  1
18  0
19  1
20  2
21  1
22  0
23  2


In [3]:
print('Base de teste reduzida:')
print(df_X_test)
print(df_y_test)

Base de teste reduzida:
      0    1    2    3
0   5.8  2.8  5.1  2.4
1   6.0  2.2  4.0  1.0
2   5.5  4.2  1.4  0.2
3   7.3  2.9  6.3  1.8
4   5.0  3.4  1.5  0.2
5   6.3  3.3  6.0  2.5
6   5.0  3.5  1.3  0.3
7   6.7  3.1  4.7  1.5
8   6.8  2.8  4.8  1.4
9   6.1  2.8  4.0  1.3
10  6.1  2.6  5.6  1.4
11  6.4  3.2  4.5  1.5
12  6.1  2.8  4.7  1.2
13  6.5  2.8  4.6  1.5
14  6.1  2.9  4.7  1.4
15  4.9  3.6  1.4  0.1
    0
0   2
1   1
2   0
3   2
4   0
5   2
6   0
7   1
8   1
9   1
10  2
11  1
12  1
13  1
14  1
15  0


In [4]:
from sklearn.impute import SimpleImputer

imp = SimpleImputer(missing_values=1.5, strategy='most_frequent')
imp.fit(new_X_train)  


print(new_X_train)
print(imp.transform(new_X_train)) 

[[6.  3.4 4.5 1.6]
 [4.8 3.1 1.6 0.2]
 [5.8 2.7 5.1 1.9]
 [5.6 2.7 4.2 1.3]
 [5.6 2.9 3.6 1.3]
 [5.5 2.5 4.  1.3]
 [6.1 3.  4.6 1.4]
 [7.2 3.2 6.  1.8]
 [5.3 3.7 1.5 0.2]
 [4.3 3.  1.1 0.1]
 [6.4 2.7 5.3 1.9]
 [5.7 3.  4.2 1.2]
 [5.4 3.4 1.7 0.2]
 [5.7 4.4 1.5 0.4]
 [6.9 3.1 4.9 1.5]
 [4.6 3.1 1.5 0.2]
 [5.9 3.  5.1 1.8]
 [5.1 2.5 3.  1.1]
 [4.6 3.4 1.4 0.3]
 [6.2 2.2 4.5 1.5]
 [7.2 3.6 6.1 2.5]
 [5.7 2.9 4.2 1.3]
 [4.8 3.  1.4 0.1]
 [7.1 3.  5.9 2.1]]
[[6.  3.4 4.5 1.6]
 [4.8 3.1 1.6 0.2]
 [5.8 2.7 5.1 1.9]
 [5.6 2.7 4.2 1.3]
 [5.6 2.9 3.6 1.3]
 [5.5 2.5 4.  1.3]
 [6.1 3.  4.6 1.4]
 [7.2 3.2 6.  1.8]
 [5.3 3.7 4.2 0.2]
 [4.3 3.  1.1 0.1]
 [6.4 2.7 5.3 1.9]
 [5.7 3.  4.2 1.2]
 [5.4 3.4 1.7 0.2]
 [5.7 4.4 4.2 0.4]
 [6.9 3.1 4.9 0.2]
 [4.6 3.1 4.2 0.2]
 [5.9 3.  5.1 1.8]
 [5.1 2.5 3.  1.1]
 [4.6 3.4 1.4 0.3]
 [6.2 2.2 4.5 0.2]
 [7.2 3.6 6.1 2.5]
 [5.7 2.9 4.2 1.3]
 [4.8 3.  1.4 0.1]
 [7.1 3.  5.9 2.1]]


2. Utilize agora os mesmos valores mais frequentes usados na base de treino na base de teste do
exercício 1.

In [5]:
imp = SimpleImputer(missing_values=1.5, strategy='most_frequent')
imp.fit(new_X_train)  

print(new_X_test)
print(imp.transform(new_X_test)) 

[[5.8 2.8 5.1 2.4]
 [6.  2.2 4.  1. ]
 [5.5 4.2 1.4 0.2]
 [7.3 2.9 6.3 1.8]
 [5.  3.4 1.5 0.2]
 [6.3 3.3 6.  2.5]
 [5.  3.5 1.3 0.3]
 [6.7 3.1 4.7 1.5]
 [6.8 2.8 4.8 1.4]
 [6.1 2.8 4.  1.3]
 [6.1 2.6 5.6 1.4]
 [6.4 3.2 4.5 1.5]
 [6.1 2.8 4.7 1.2]
 [6.5 2.8 4.6 1.5]
 [6.1 2.9 4.7 1.4]
 [4.9 3.6 1.4 0.1]]
[[5.8 2.8 5.1 2.4]
 [6.  2.2 4.  1. ]
 [5.5 4.2 1.4 0.2]
 [7.3 2.9 6.3 1.8]
 [5.  3.4 4.2 0.2]
 [6.3 3.3 6.  2.5]
 [5.  3.5 1.3 0.3]
 [6.7 3.1 4.7 0.2]
 [6.8 2.8 4.8 1.4]
 [6.1 2.8 4.  1.3]
 [6.1 2.6 5.6 1.4]
 [6.4 3.2 4.5 0.2]
 [6.1 2.8 4.7 1.2]
 [6.5 2.8 4.6 0.2]
 [6.1 2.9 4.7 1.4]
 [4.9 3.6 1.4 0.1]]


3. Padronize a base de treino do exercício 1 e utilize os mesmos fatores de normalização para
padronizar a base de teste.

In [6]:
from sklearn import preprocessing
max_abs_scaler = preprocessing.MaxAbsScaler()

X_train_maxabs = max_abs_scaler.fit_transform(new_X_train)
print ('Train')
print(new_X_train)
print(X_train_maxabs)

X_test_maxabs = max_abs_scaler.transform(new_X_test)
print ('\nTest')
print(new_X_test)
print(X_test_maxabs)

print ('\nMáximos')
print(max_abs_scaler.scale_) 

Train
[[6.  3.4 4.5 1.6]
 [4.8 3.1 1.6 0.2]
 [5.8 2.7 5.1 1.9]
 [5.6 2.7 4.2 1.3]
 [5.6 2.9 3.6 1.3]
 [5.5 2.5 4.  1.3]
 [6.1 3.  4.6 1.4]
 [7.2 3.2 6.  1.8]
 [5.3 3.7 1.5 0.2]
 [4.3 3.  1.1 0.1]
 [6.4 2.7 5.3 1.9]
 [5.7 3.  4.2 1.2]
 [5.4 3.4 1.7 0.2]
 [5.7 4.4 1.5 0.4]
 [6.9 3.1 4.9 1.5]
 [4.6 3.1 1.5 0.2]
 [5.9 3.  5.1 1.8]
 [5.1 2.5 3.  1.1]
 [4.6 3.4 1.4 0.3]
 [6.2 2.2 4.5 1.5]
 [7.2 3.6 6.1 2.5]
 [5.7 2.9 4.2 1.3]
 [4.8 3.  1.4 0.1]
 [7.1 3.  5.9 2.1]]
[[0.83333333 0.77272727 0.73770492 0.64      ]
 [0.66666667 0.70454545 0.26229508 0.08      ]
 [0.80555556 0.61363636 0.83606557 0.76      ]
 [0.77777778 0.61363636 0.68852459 0.52      ]
 [0.77777778 0.65909091 0.59016393 0.52      ]
 [0.76388889 0.56818182 0.6557377  0.52      ]
 [0.84722222 0.68181818 0.75409836 0.56      ]
 [1.         0.72727273 0.98360656 0.72      ]
 [0.73611111 0.84090909 0.24590164 0.08      ]
 [0.59722222 0.68181818 0.18032787 0.04      ]
 [0.88888889 0.61363636 0.86885246 0.76      ]
 [0.79166667 0.68181

4. Discretize a base Z_Train usando a estratégia de igual frequência nos intervalos e utilize os
mesmos intervalos para discretizar a base Z_Test. Repita depois usando a estratégia de igual tamanho dos intervalos. Atenção: crie novas bases para não alterar a definição original de Z_Train e Z_Test.

In [7]:
Z_train = new_X_train.copy()
Z_teste = new_X_test.copy()

est = preprocessing.KBinsDiscretizer(n_bins=[3, 2, 2, 4], 
                                     encode='ordinal').fit(Z_train)
X_bin = est.transform(Z_teste)
print(X_bin)




[[1. 0. 1. 3.]
 [2. 0. 0. 1.]
 [1. 1. 0. 0.]
 [2. 0. 1. 3.]
 [0. 1. 0. 0.]
 [2. 1. 1. 3.]
 [0. 1. 0. 1.]
 [2. 1. 1. 2.]
 [2. 0. 1. 2.]
 [2. 0. 0. 2.]
 [2. 0. 1. 2.]
 [2. 1. 1. 2.]
 [2. 0. 1. 1.]
 [2. 0. 1. 2.]
 [2. 0. 1. 2.]
 [0. 1. 0. 0.]]


5. Leia a base de dados breast cancer e execute 3 rodadas de validação cruzada aninhada
estratificada, porém use padronização em todas as características da base. Use o classificador KNN
com k = {1, 3, 5}. Apresente a acurácia obtida em cada fold de teste, assim como a média da acurácia, desvio padrão e intervalo de confiança.

In [8]:
from sklearn.datasets import load_breast_cancer
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score, RepeatedStratifiedKFold
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from scipy import stats
import numpy as np

breast = load_breast_cancer()
breast_X = breast.data
breast_y = breast.target

kNN = KNeighborsClassifier()

grade={'estimator__n_neighbors': [1,3,5]}
rkf = RepeatedStratifiedKFold(n_splits=10, n_repeats=3)
scalar = StandardScaler()
pipeline = Pipeline([('transformer', scalar), ('estimator', kNN)])

gs = GridSearchCV(estimator=pipeline, param_grid = grade, 
                  scoring='accuracy', cv = 4)

scores = cross_val_score(gs, breast_X, breast_y, scoring='accuracy', 
                         cv = rkf)

print(scores)

mean = scores.mean()
std = scores.std()
inf, sup = stats.norm.interval(0.95, loc=mean, 
                               scale=std/np.sqrt(len(scores)))

print("\nMean Accuracy: %0.2f Standard Deviation: %0.2f" % (mean, std))
print ("Accuracy Confidence Interval (95%%): (%0.2f, %0.2f)\n" % 
       (inf, sup)) 

[0.96491228 1.         0.94736842 0.9122807  0.92982456 1.
 0.96491228 0.96491228 0.98245614 0.98214286 0.94736842 0.94736842
 0.98245614 0.98245614 0.96491228 0.96491228 0.96491228 0.98245614
 0.94736842 0.96428571 0.98245614 0.98245614 0.94736842 0.9122807
 0.92982456 0.92982456 0.96491228 0.96491228 1.         0.96428571]

Mean Accuracy: 0.96 Standard Deviation: 0.02
Accuracy Confidence Interval (95%): (0.95, 0.97)



6. Crie um dataset com 5 exemplos com dados nominais para condições do dia com temperatura
(baixa, média e alta), aparência (ensolarado, nublado, chuvoso) e vento (pouco, muito). Transforme os dados de temperatura e vento para o formato ordinal e o de aparência para o formato binário.

In [9]:
import pandas as pd
from sklearn import preprocessing

data = [
    ['baixa', 'nublado', 'muito'],
    ['média', 'chuvoso', 'muito'],
    ['alta', 'ensolarado', 'pouco'],
    ['média', 'ensolarado', 'pouco'],
    ['baixa', 'nublado', 'muito']
]

df = pd.DataFrame(data)

print(df)

df.columns = ['temperature', 'weather', 'wind']

enc = preprocessing.OrdinalEncoder()
enc.fit(df[['temperature', 'weather']]) 
df[['temperature', 'weather']] = enc.transform(df[['temperature', 'weather']])
print('\n', df)

wind_mapping = {'pouco': False, 'muito': True}
df['wind'] = df['wind'].map(wind_mapping)
print('\n', df)

# Solução alternativa
df = pd.get_dummies(df[df.columns])
print('\n', df)



       0           1      2
0  baixa     nublado  muito
1  média     chuvoso  muito
2   alta  ensolarado  pouco
3  média  ensolarado  pouco
4  baixa     nublado  muito

    temperature  weather   wind
0          1.0      2.0  muito
1          2.0      0.0  muito
2          0.0      1.0  pouco
3          2.0      1.0  pouco
4          1.0      2.0  muito

    temperature  weather   wind
0          1.0      2.0   True
1          2.0      0.0   True
2          0.0      1.0  False
3          2.0      1.0  False
4          1.0      2.0   True

    temperature  weather   wind
0          1.0      2.0   True
1          2.0      0.0   True
2          0.0      1.0  False
3          2.0      1.0  False
4          1.0      2.0   True


7. Compare o desempenho (acurácia média, desvio padrão e intervalo de confiança a 95%) do
método PCA com três componentes com o método de seleção univariada de características usando
quiquadrado e selecionando 3 características no dataset wine. Use o classificador Vizinho Mais Próximo (k = 1) e o método de validação cruzada com 10 folds.

In [21]:
from sklearn.datasets import load_wine
from sklearn.decomposition import PCA

wine = load_wine()

wine_X = wine.data
wine_y = wine.target


In [22]:
# Aplicando PCA
pca = PCA(n_components = 3)
X_ts = pca.fit_transform(wine_X)

print(wine_X)
print(X_ts)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]
[[ 3.18562979e+02  2.14921307e+01  3.13073470e+00]
 [ 3.03097420e+02 -5.36471768e+00  6.82283550e+00]
 [ 4.38061133e+02 -6.53730945e+00 -1.11322298e+00]
 [ 7.33240139e+02  1.92729032e-01 -9.17257016e-01]
 [-1.15714285e+01  1.84899946e+01 -5.54422076e-01]
 [ 7.03231192e+02 -3.32158674e-01  9.49375334e-01]
 [ 5.42971581e+02 -1.35189666e+01  2.12694283e+00]
 [ 5.48401860e+02  1.14494324e+01  4.04924202e-02]
 [ 2.98036863e+02 -8.18015784e+00  3.88097517e+00]
 [ 2.98049553e+02 -7.10154294e+00  1.55845533e+00]
 [ 7.63079712e+02 -8.33431723e+00 -1.88629037e+00]
 [ 5.32943228e+02 -1.42876338e+

In [23]:
# Aplicando seleção univariada de características
from sklearn.feature_selection import SelectKBest

X_b = SelectKBest(k = 3).fit_transform(wine_X, wine_y)
print(wine_X)
print (X_b)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]
[[3.060e+00 3.920e+00 1.065e+03]
 [2.760e+00 3.400e+00 1.050e+03]
 [3.240e+00 3.170e+00 1.185e+03]
 [3.490e+00 3.450e+00 1.480e+03]
 [2.690e+00 2.930e+00 7.350e+02]
 [3.390e+00 2.850e+00 1.450e+03]
 [2.520e+00 3.580e+00 1.290e+03]
 [2.510e+00 3.580e+00 1.295e+03]
 [2.980e+00 2.850e+00 1.045e+03]
 [3.150e+00 3.550e+00 1.045e+03]
 [3.320e+00 3.170e+00 1.510e+03]
 [2.430e+00 2.820e+00 1.280e+03]
 [2.760e+00 2.900e+00 1.320e+03]
 [3.690e+00 2.730e+00 1.150e+03]
 [3.640e+00 3.000e+00 1.547e+03]
 [2.910e+00 2.880e+00 1.310e+03]
 [3.140e+00 2.650e+00 1.280e+03]
 [3.400e+00 2.570e+00 1.130e+03

In [24]:
# Treinando e fazendo validação cruzada com os dados após PCA
kNN = KNeighborsClassifier()

grade={'estimator__n_neighbors': [1]}
rkf = RepeatedStratifiedKFold(n_splits=10, n_repeats=3)
scalar = StandardScaler()
pipeline = Pipeline([('transformer', scalar), ('estimator', kNN)])

gs = GridSearchCV(estimator=pipeline, param_grid = grade, 
                  scoring='accuracy', cv = 4)

scores = cross_val_score(gs, X_ts, wine_y, scoring='accuracy', 
                         cv = rkf)

print(scores)

mean = scores.mean()
std = scores.std()
inf, sup = stats.norm.interval(0.95, loc=mean, 
                               scale=std/np.sqrt(len(scores)))

print("\nMean Accuracy: %0.2f Standard Deviation: %0.2f" % (mean, std))
print ("Accuracy Confidence Interval (95%%): (%0.2f, %0.2f)\n" % 
       (inf, sup)) 

[0.38888889 0.77777778 0.83333333 0.83333333 0.83333333 0.66666667
 0.77777778 0.77777778 0.70588235 0.82352941 0.77777778 0.77777778
 0.66666667 0.77777778 0.94444444 0.55555556 0.66666667 0.77777778
 0.70588235 0.76470588 0.66666667 0.72222222 0.94444444 0.66666667
 0.88888889 0.72222222 0.72222222 0.72222222 0.82352941 0.64705882]

Mean Accuracy: 0.75 Standard Deviation: 0.11
Accuracy Confidence Interval (95%): (0.71, 0.78)



In [25]:
# Treinando e fazendo validação cruzada com os dados após seleção de características univariada
kNN = KNeighborsClassifier()

grade={'estimator__n_neighbors': [1]}
rkf = RepeatedStratifiedKFold(n_splits=10, n_repeats=3)
scalar = StandardScaler()
pipeline = Pipeline([('transformer', scalar), ('estimator', kNN)])

gs = GridSearchCV(estimator=pipeline, param_grid = grade, 
                  scoring='accuracy', cv = 4)

scores = cross_val_score(gs, X_b, wine_y, scoring='accuracy', 
                         cv = rkf)

print(scores)

mean = scores.mean()
std = scores.std()
inf, sup = stats.norm.interval(0.95, loc=mean, 
                               scale=std/np.sqrt(len(scores)))

print("\nMean Accuracy: %0.2f Standard Deviation: %0.2f" % (mean, std))
print ("Accuracy Confidence Interval (95%%): (%0.2f, %0.2f)\n" % 
       (inf, sup)) 

[0.94444444 0.94444444 0.88888889 0.94444444 0.94444444 0.94444444
 0.88888889 0.88888889 0.82352941 1.         0.88888889 0.94444444
 0.83333333 1.         0.94444444 1.         0.88888889 0.88888889
 0.94117647 0.82352941 0.88888889 0.83333333 0.88888889 1.
 0.83333333 0.94444444 0.94444444 0.94444444 0.94117647 0.88235294]

Mean Accuracy: 0.92 Standard Deviation: 0.05
Accuracy Confidence Interval (95%): (0.90, 0.93)



8. Obtenha o desempenho (acurácia média, desvio padrão e intervalo de confiança a 95%) do
método de seleção multivariada de características com seleção sequencial para frente e selecionando
3 características no dataset wine. Use o classificador Vizinho Mais Próximo (k = 1) e o método de validação cruzada com 10 folds.

In [27]:
from sklearn.feature_selection import SequentialFeatureSelector

oneNN = KNeighborsClassifier(n_neighbors = 1)

sfs_forward = SequentialFeatureSelector(oneNN, n_features_to_select=3,
                direction='forward').fit_transform(wine_X, wine_y)

print(wine_X)
print(sfs_forward)

[[ 3.06      0.28      5.64    ]
 [ 2.76      0.26      4.38    ]
 [ 3.24      0.3       5.68    ]
 [ 3.49      0.24      7.8     ]
 [ 2.69      0.39      4.32    ]
 [ 3.39      0.34      6.75    ]
 [ 2.52      0.3       5.25    ]
 [ 2.51      0.31      5.05    ]
 [ 2.98      0.29      5.2     ]
 [ 3.15      0.22      7.22    ]
 [ 3.32      0.22      5.75    ]
 [ 2.43      0.26      5.      ]
 [ 2.76      0.29      5.6     ]
 [ 3.69      0.43      5.4     ]
 [ 3.64      0.29      7.5     ]
 [ 2.91      0.3       7.3     ]
 [ 3.14      0.33      6.2     ]
 [ 3.4       0.4       6.6     ]
 [ 3.93      0.32      8.7     ]
 [ 3.03      0.17      5.1     ]
 [ 3.17      0.24      5.65    ]
 [ 2.41      0.25      4.5     ]
 [ 2.88      0.27      3.8     ]
 [ 2.37      0.26      3.93    ]
 [ 2.61      0.28      3.52    ]
 [ 2.68      0.47      3.58    ]
 [ 2.94      0.34      4.8     ]
 [ 2.19      0.27      3.95    ]
 [ 2.97      0.37      4.5     ]
 [ 2.33      0.26      4.7     ]
 [ 3.25   

In [29]:
# Aplicando validação cruzada após seleção sequencial para frente
rkf = RepeatedStratifiedKFold(n_splits=10, n_repeats=3)

scores = cross_val_score(oneNN, sfs_forward, wine_y, scoring='accuracy', 
                         cv = rkf)

print(scores)

mean = scores.mean()
std = scores.std()
inf, sup = stats.norm.interval(0.95, loc=mean, 
                               scale=std/np.sqrt(len(scores)))

print("\nMean Accuracy: %0.2f Standard Deviation: %0.2f" % (mean, std))
print ("Accuracy Confidence Interval (95%%): (%0.2f, %0.2f)\n" % 
       (inf, sup)) 

[1.         1.         0.88888889 0.94444444 0.94444444 1.
 0.88888889 0.94444444 0.94117647 0.94117647 0.94444444 0.94444444
 0.88888889 0.88888889 0.94444444 0.94444444 1.         1.
 0.88235294 1.         1.         1.         0.83333333 0.94444444
 1.         0.88888889 0.88888889 1.         0.88235294 1.        ]

Mean Accuracy: 0.95 Standard Deviation: 0.05
Accuracy Confidence Interval (95%): (0.93, 0.96)

